sg = Image.create!(name: "starbucks_green", title: "Starbucks green")
sb = Image.create!(name: "starbucks_blue", title: "Starbucks blue")
sr = Image.create!(name: "starbucks_red", title: "Starbucks red")

Part.create!(position: 1, image: sg)
Part.create!(position: 1, image: sg)
Part.create!(position: 3, image: sg)
Part.create!(position: 5, image: sg)

Part.create!(position: 1, image: sg)
Part.create!(position: 2, image: sg)
Part.create!(position: 3, image: sg)
Part.create!(position: 4, image: sg)
Part.create!(position: 5, image: sg)
Part.create!(position: 6, image: sg)
Part.create!(position: 7, image: sg)
Part.create!(position: 8, image: sg)
Part.create!(position: 9, image: sg)
